font_family Iosevka Nerd Font Mono
font_size 10
window_padding_width 15
background_opacity 0.95
# background_blur 256

adjust_line_height 115%

tab_bar_style powerline
tab_powerline_style round

remember_window_size no
initial_window_width 720
initial_window_height 512

wheel_scroll_multiplier 1
touch_scroll_multiplier 5

cursor_trail 1

macos_option_as_alt yes
