#!/bin/sh
~/.scripts/startup.sh &> /dev/null &
SXHKD_SHELL=sh sxhkd &> /dev/null &
SXHKD_SHELL=sh sxhkd -c ~/.config/sxhkd/bspwm &> /dev/null &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            1
bspc config window_gap              15
# bspc config top_padding             35
bspc config split_ratio             0.5

bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config single_monocle          true

bspc config focused_border_color    "#49678B"
bspc config presel_feedback_color   "#272F38"

bspc config border_radius           5

bspc rule -a discord desktop='^1'
bspc rule -a Zathura state=tiled
bspc rule -a WM_FLOATING state=floating
bspc rule -a deepin-calculator sticky=on hidden=on
