#!/bin/sh
~/.scripts/startup.sh &> /dev/null &
sxhkd &> /dev/null &
sxhkd -c ~/.config/sxhkd/bspwm &> /dev/null &

# bspc monitor -d 1 2 3 4 5 6 7 8 9 0
~/.config/bspwm/configure_monitors

bspc config external_rules_command "$(dirname "$0")/external_rules"

bspc config border_width            1
bspc config window_gap              30
# bspc config window_gap              0
# bspc config top_padding             35
bspc config split_ratio             0.5

bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config single_monocle          true

bspc config normal_border_color     "#313244"
bspc config focused_border_color    "#b4befe"
bspc config presel_feedback_color   "#272F38"

# bspc config border_radius           5

# bspc rule -a discord desktop='^1'
# bspc rule -a thunderbird desktop='^9'
# bspc rule -a spotify desktop='^10'
bspc rule -a Zathura state=tiled
bspc rule -a WM_FLOATING state=floating
bspc rule -a deepin-calculator sticky=on hidden=on border=off
bspc rule -a deepin-editor state=floating border=off
bspc rule -a Gnome-calculator state=floating
bspc rule -a Nextcloud state=floating
bspc rule -a 'zoom ' state=floating center=on follow=on border=off
bspc rule -a Ulauncher border=off
