#!/bin/sh
monitors=$(bspc query -M)
monitors_except_last=$(echo "$monitors" | head -n -1)
last_monitor=$(echo "$monitors" | tail -n 1)

n=$(echo "$monitors" | wc -l)
desktops_per_monitor=$((10 / n))

set_monitor() {
    # shellcheck disable=SC2046
    bspc monitor "$1" -d $(echo "$2 $3" | awk 'BEGIN { ORS=" " }; { for (i=$1; i < $1 + $2; i++) print i }')
}

i=1
for monitor in $monitors_except_last; do
    set_monitor "$monitor" $i $desktops_per_monitor
    i=$((i+desktops_per_monitor))
done

set_monitor "$last_monitor" $i $((10 - i + 1))
