#!/bin/sh
delay=0.1

for i in $(seq 1 2); do
    xset led named "Caps Lock"
    xset led named "Num Lock"
    sleep $delay
    xset -led named "Caps Lock"
    xset -led named "Num Lock"
    sleep $delay
done
