#!/bin/sh
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
for desktop in $(bspc query -D); do
    bspc desktop "$desktop" --to-monitor eDP1
done
bspc monitor HDMI2 --remove
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
