#!/bin/sh
# monitor=$(xrandr | grep 'primary' | cut -d' ' -f1)
monitor="$1"
bspc monitor "$monitor" -d 1 2 3 4 5 6 7 8 9 10
for desktop in $(bspc query -D); do
    bspc desktop "$desktop" --to-monitor "$monitor"
done
for m in $(bspc query -M --names | grep -v "$monitor"); do
    bspc monitor "$m" --remove
done
bspc monitor "$monitor" -d 1 2 3 4 5 6 7 8 9 10
