#!/bin/sh
auth=$(jq -r . ~/.config/twitch-auth.json)
client_id=$(echo $auth | jq -r .clientId)
token=$(echo $auth | jq -r .oauthToken)

get() {
  curl -s \
    -H Client-ID:$client_id \
    -H "Authorization:Bearer $token" \
    https://api.twitch.tv/helix/$1
}

id=$(get users?login=$1 | jq -r .data[0].id)
get "users/follows?to_id=$id&after=$2" | jq -S
