#!/usr/bin/env python
# Original Author: Marcin Kocur, attribution license:
#     https://creativecommons.org/licenses/by/4.0/
# From https://wiki.archlinux.org/index.php/spotify#pactl_(pulseaudio)
# (modified)
from sys import argv
from subprocess import check_output, run

app = '"Spotify"'

pactl = check_output(['pactl', 'list', 'sink-inputs']).decode().split('\n\n')
sink = next(p.split() for p in reversed(pactl) if app in p)

volume = int(sink[sink.index("Volume:") + 4][:-1])
sink_id = sink[2][1:]

offset = int(argv[1])
if volume + offset > 100:
    run(['pactl', 'set-sink-input-volume', sink_id, '100%'])
else:
    run(['pactl', 'set-sink-input-volume', sink_id, f'{offset}%'])
